acidsplash = { "name":"Acid Splash", "level":"Cantrip", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 211" }
bladeward = { "name":"Blade Ward", "level":"Cantrip", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 218" }
chilltouch = { "name":"Chill Touch", "level":"Cantrip", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 221" }
controlflames = { "name":"Control Flames", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"S", "source":"EE 16, Xanathar's Guide to Everything page 152" }
createbonfire = { "name":"Create Bonfire", "level":"Cantrip", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"EE 16, Xanathar's Guide to Everything page 152" }
dancinglights = { "name":"Dancing Lights", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 230" }
druidcraft = { "name":"Druidcraft", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 236" }
eldritchblast = { "name":"Eldritch Blast", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 237" }
firebolt = { "name":"Fire Bolt", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 242" }
friends = { "name":"Friends", "level":"Cantrip", "school":"Enchantment", "castingtime":"1 action", "components":"SM", "source":"Player Handbook page 244" }
frostbite = { "name":"Frostbite", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"EE 18, Xanathar's Guide to Everything page 156" }
guidance = { "name":"Guidance", "level":"Cantrip", "school":"Divination", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 248" }
gust = { "name":"Gust", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 19, Xanathar's Guide to Everything page 157" }
infestation = { "name":"Infestation", "level":"Cantrip", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Xanathar's Guide to Everything page 158" }
light = { "name":"Light", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VM", "source":"Player Handbook page 255" }
magehand = { "name":"Mage Hand", "level":"Cantrip", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 256" }
magicstone = { "name":"Magic Stone", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VS", "source":"EE 20, Xanathar's Guide to Everything page 160" }
mending = { "name":"Mending", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 259" }
message = { "name":"Message", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 259" }
minorillusion = { "name":"Minor Illusion", "level":"Cantrip", "school":"Illusion", "castingtime":"1 action", "components":"SM", "source":"Player Handbook page 260" }
moldearth = { "name":"Mold Earth", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"S", "source":"EE 21, Xanathar's Guide to Everything page 162" }
poisonspray = { "name":"Poison Spray", "level":"Cantrip", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 266" }
prestidigitation = { "name":"Prestidigitation", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 267" }
primalsavagery = { "name":"Primal Savagery", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"S", "source":"Xanathar's Guide to Everything page 163" }
produceflame = { "name":"Produce Flame", "level":"Cantrip", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 269" }
rayoffrost = { "name":"Ray of Frost", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 271" }
resistance = { "name":"Resistance", "level":"Cantrip", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 272" }
sacredflame = { "name":"Sacred Flame", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 272" }
shapewater = { "name":"Shape Water", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"S", "source":"EE 21" }
shillelagh = { "name":"Shillelagh", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VSM", "source":"Player Handbook page 275" }
shockinggrasp = { "name":"Shocking Grasp", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 275" }
sparethedying = { "name":"Spare the Dying", "level":"Cantrip", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 277" }
thaumaturgy = { "name":"Thaumaturgy", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 282" }
thornwhip = { "name":"Thorn Whip", "level":"Cantrip", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 282" }
thunderclap = { "name":"Thunderclap", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"S", "source":"EE 22, Xanathar's Guide to Everything page 168" }
tollthedead = { "name":"Toll the Dead", "level":"Cantrip", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 169" }
truestrike = { "name":"True Strike", "level":"Cantrip", "school":"Divination", "castingtime":"1 action", "components":"S", "source":"Player Handbook page 284" }
viciousmockery = { "name":"Vicious Mockery", "level":"Cantrip", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 285" }
wordofradiance = { "name":"Word of Radiance", "level":"Cantrip", "school":"Evocation", "castingtime":"1 action", "components":"VM", "source":"Xanathar's Guide to Everything page 171" }
absorbelements = { "name":"Absorb Elements", "level":"1st", "school":"Abjuration", "castingtime":"1 reaction", "components":"S", "source":"EE 15, Xanathar's Guide to Everything page 150" }
alarm = { "name":"Alarm", "level":"1st", "school":"Abjuration", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 211" }
animalfriendship = { "name":"Animal Friendship", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 212" }
arcaneweapon = { "name":"Arcane Weapon", "level":"1st", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VS", "source":"ua" }
armorofagathys = { "name":"Armor of Agathys", "level":"1st", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 215" }
armsofhadar = { "name":"Arms of Hadar", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 215" }
bane = { "name":"Bane", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 216" }
beastbond = { "name":"Beast Bond", "level":"1st", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"EE 15, Xanathar's Guide to Everything page 150" }
bless = { "name":"Bless", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 219" }
burninghands = { "name":"Burning Hands", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 220" }
catapult = { "name":"Catapult", "level":"1st", "school":"Transmutation", "castingtime":"1 action", "components":"S", "source":"EE 15, Xanathar's Guide to Everything page 150" }
causefear = { "name":"Cause Fear", "level":"1st", "school":"Necromancy", "castingtime":"1 action", "components":"V", "source":"Xanathar's Guide to Everything page 151" }
ceremony = { "name":"Ceremony", "level":"1st", "school":"Abjuration", "castingtime":"1 hour", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 151" }
chaosbolt = { "name":"Chaos Bolt", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 151" }
charmperson = { "name":"Charm Person", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 221" }
chromaticorb = { "name":"Chromatic Orb", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 221" }
colorspray = { "name":"Color Spray", "level":"1st", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 222" }
command = { "name":"Command", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 223" }
compelledduel = { "name":"Compelled Duel", "level":"1st", "school":"Enchantment", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 224" }
comprehendlanguages = { "name":"Comprehend Languages", "level":"1st", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 224" }
createordestroywater = { "name":"Create or Destroy Water", "level":"1st", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 229" }
curewounds = { "name":"Cure Wounds", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 230" }
detectevilandgood = { "name":"Detect Evil and Good", "level":"1st", "school":"Divination", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 231" }
detectmagic = { "name":"Detect Magic", "level":"1st", "school":"Divination", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 231" }
detectpoisonanddisease = { "name":"Detect Poison and Disease", "level":"1st", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 231" }
disguiseself = { "name":"Disguise Self", "level":"1st", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 233" }
dissonantwhispers = { "name":"Dissonant Whispers", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 234" }
divinefavor = { "name":"Divine Favor", "level":"1st", "school":"Evocation", "castingtime":"1 bonus action", "components":"VS", "source":"Player Handbook page 234" }
earthtremor = { "name":"Earth Tremor", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"EE 17, Xanathar's Guide to Everything page 155" }
ensnaringstrike = { "name":"Ensnaring Strike", "level":"1st", "school":"Conjuration", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 237" }
entangle = { "name":"Entangle", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 238" }
expeditiousretreat = { "name":"Expeditious Retreat", "level":"1st", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VS", "source":"Player Handbook page 238" }
faeriefire = { "name":"Faerie Fire", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 239" }
falselife = { "name":"False Life", "level":"1st", "school":"Necromancy", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 239" }
featherfall = { "name":"Feather Fall", "level":"1st", "school":"Transmutation", "castingtime":"1 reaction", "components":"VM", "source":"Player Handbook page 239" }
findfamiliar = { "name":"Find Familiar", "level":"1st", "school":"Conjuration", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 240" }
fogcloud = { "name":"Fog Cloud", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 243" }
goodberry = { "name":"Goodberry", "level":"1st", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 246" }
grease = { "name":"Grease", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 246" }
guidingbolt = { "name":"Guiding Bolt", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 248" }
hailofthorns = { "name":"Hail of Thorns", "level":"1st", "school":"Conjuration", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 249" }
healingword = { "name":"Healing Word", "level":"1st", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 250" }
hellishrebuke = { "name":"Hellish Rebuke", "level":"1st", "school":"Evocation", "castingtime":"1 reaction", "components":"VS", "source":"Player Handbook page 250" }
heroism = { "name":"Heroism", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 250" }
hex = { "name":"Hex", "level":"1st", "school":"Enchantment", "castingtime":"1 bonus action", "components":"VSM", "source":"Player Handbook page 251" }
huntersmark = { "name":"Hunter's Mark", "level":"1st", "school":"Divination", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 251" }
iceknife = { "name":"Ice Knife", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"SM", "source":"EE 19, Xanathar's Guide to Everything page 157" }
identify = { "name":"Identify", "level":"1st", "school":"Divination", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 252" }
illusoryscript = { "name":"Illusory Script", "level":"1st", "school":"Illusion", "castingtime":"1 minute", "components":"SMgp", "source":"Player Handbook page 252" }
inflictwounds = { "name":"Inflict Wounds", "level":"1st", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 253" }
jump = { "name":"Jump", "level":"1st", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 254" }
longstrider = { "name":"Longstrider", "level":"1st", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 256" }
magearmor = { "name":"Mage Armor", "level":"1st", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 256" }
magicmissile = { "name":"Magic Missile", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 257" }
protectionfromevilandgood = { "name":"Protection from Evil and Good", "level":"1st", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 270" }
purifyfoodanddrink = { "name":"Purify Food and Drink", "level":"1st", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 270" }
rayofsickness = { "name":"Ray of Sickness", "level":"1st", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 271" }
sanctuary = { "name":"Sanctuary", "level":"1st", "school":"Abjuration", "castingtime":"1 bonus action", "components":"VSM", "source":"Player Handbook page 272" }
searingsmite = { "name":"Searing Smite", "level":"1st", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 274" }
shield = { "name":"Shield", "level":"1st", "school":"Abjuration", "castingtime":"1 reaction", "components":"VS", "source":"Player Handbook page 275" }
shieldoffaith = { "name":"Shield of Faith", "level":"1st", "school":"Abjuration", "castingtime":"1 bonus action", "components":"VSM", "source":"Player Handbook page 275" }
silentimage = { "name":"Silent Image", "level":"1st", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 276" }
sleep = { "name":"Sleep", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 276" }
snare = { "name":"Snare", "level":"1st", "school":"Abjuration", "castingtime":"1 minute", "components":"SMgp", "source":"Xanathar's Guide to Everything page 165" }
speakwithanimals = { "name":"Speak with Animals", "level":"1st", "school":"Divination", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 277" }
tashashideouslaughter = { "name":"Tasha's Hideous Laughter", "level":"1st", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 280" }
tensersfloatingdisk = { "name":"Tenser's Floating Disk", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 282" }
thunderoussmite = { "name":"Thunderous Smite", "level":"1st", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 282" }
thunderwave = { "name":"Thunderwave", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 282" }
unseenservant = { "name":"Unseen Servant", "level":"1st", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 284" }
witchbolt = { "name":"Witch Bolt", "level":"1st", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 289" }
wrathfulsmite = { "name":"Wrathful Smite", "level":"1st", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 289" }
zephyrstrike = { "name":"Zephyr Strike", "level":"1st", "school":"Transmutation", "castingtime":"1 bonus action", "components":"V", "source":"Xanathar's Guide to Everything page 171" }
aganazzarsscorcher = { "name":"Aganazzar's Scorcher", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 15, Xanathar's Guide to Everything page 150" }
aid = { "name":"Aid", "level":"2nd", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 211" }
alterself = { "name":"Alter Self", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 211" }
animalmessenger = { "name":"Animal Messenger", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 212" }
arcanelock = { "name":"Arcane Lock", "level":"2nd", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 215" }
augury = { "name":"Augury", "level":"2nd", "school":"Divination", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 215" }
barkskin = { "name":"Barkskin", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 217" }
beastsense = { "name":"Beast Sense", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"S", "source":"Player Handbook page 217" }
blindnessdeafness = { "name":"Blindness/Deafness", "level":"2nd", "school":"Necromancy", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 219" }
blur = { "name":"Blur", "level":"2nd", "school":"Illusion", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 219" }
brandingsmite = { "name":"Branding Smite", "level":"2nd", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 219" }
calmemotions = { "name":"Calm Emotions", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 221" }
cloudofdaggers = { "name":"Cloud of Daggers", "level":"2nd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 222" }
continualflame = { "name":"Continual Flame", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 227" }
cordonofarrows = { "name":"Cordon of Arrows", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 228" }
crownofmadness = { "name":"Crown of Madness", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 229" }
darkness = { "name":"Darkness", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VM", "source":"Player Handbook page 230" }
darkvision = { "name":"Darkvision", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 230" }
detectthoughts = { "name":"Detect Thoughts", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 231" }
dragonsbreath = { "name":"Dragon's Breath", "level":"2nd", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VSM", "source":"Xanathar's Guide to Everything page 154" }
dustdevil = { "name":"Dust Devil", "level":"2nd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"EE 17, Xanathar's Guide to Everything page 154" }
earthbind = { "name":"Earthbind", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"V", "source":"EE 17, Xanathar's Guide to Everything page 154" }
enhanceability = { "name":"Enhance Ability", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 237" }
enlargereduce = { "name":"Enlarge/Reduce", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 237" }
enthrall = { "name":"Enthrall", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 238" }
findsteed = { "name":"Find Steed", "level":"2nd", "school":"Conjuration", "castingtime":"10 minutes", "components":"VS", "source":"Player Handbook page 240" }
findtraps = { "name":"Find Traps", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 241" }
flameblade = { "name":"Flame Blade", "level":"2nd", "school":"Evocation", "castingtime":"1 bonus action", "components":"VSM", "source":"Player Handbook page 242" }
flamingsphere = { "name":"Flaming Sphere", "level":"2nd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 242" }
gentlerepose = { "name":"Gentle Repose", "level":"2nd", "school":"Necromancy", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 245" }
gustofwind = { "name":"Gust of Wind", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 248" }
healingspirit = { "name":"Healing Spirit", "level":"2nd", "school":"Conjuration", "castingtime":"1 bonus action", "components":"VS", "source":"Xanathar's Guide to Everything page 157" }
heatmetal = { "name":"Heat Metal", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 250" }
holdperson = { "name":"Hold Person", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 251" }
invisibility = { "name":"Invisibility", "level":"2nd", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 254" }
knock = { "name":"Knock", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 254" }
lesserrestoration = { "name":"Lesser Restoration", "level":"2nd", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 255" }
levitate = { "name":"Levitate", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 255" }
locateanimalsorplants = { "name":"Locate Animals or Plants", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 256" }
locateobject = { "name":"Locate Object", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 256" }
magicmouth = { "name":"Magic Mouth", "level":"2nd", "school":"Illusion", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 257" }
magicweapon = { "name":"Magic Weapon", "level":"2nd", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VS", "source":"Player Handbook page 257" }
maximiliansearthengrasp = { "name":"Maximilian's Earthen Grasp", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"EE 20, Xanathar's Guide to Everything page 161" }
melfsacidarrow = { "name":"Melf's Acid Arrow", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 259" }
mindspike = { "name":"Mind Spike", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"S", "source":"Xanathar's Guide to Everything page 162" }
mirrorimage = { "name":"Mirror Image", "level":"2nd", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 260" }
mistystep = { "name":"Misty Step", "level":"2nd", "school":"Conjuration", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 260" }
moonbeam = { "name":"Moonbeam", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 261" }
nystulsmagicaura = { "name":"Nystul's Magic Aura", "level":"2nd", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 263" }
passwithouttrace = { "name":"Pass without Trace", "level":"2nd", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 264" }
phantasmalforce = { "name":"Phantasmal Force", "level":"2nd", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 264" }
prayerofhealing = { "name":"Prayer of Healing", "level":"2nd", "school":"Evocation", "castingtime":"10 minutes", "components":"V", "source":"Player Handbook page 267" }
protectionfrompoison = { "name":"Protection from Poison", "level":"2nd", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 270" }
pyrotechnics = { "name":"Pyrotechnics", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 21, Xanathar's Guide to Everything page 163" }
rayofenfeeblement = { "name":"Ray of Enfeeblement", "level":"2nd", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 271" }
ropetrick = { "name":"Rope Trick", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 272" }
scorchingray = { "name":"Scorching Ray", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 273" }
seeinvisibility = { "name":"SEE Invisibility", "level":"2nd", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 274" }
shadowblade = { "name":"Shadow Blade", "level":"2nd", "school":"Illusion", "castingtime":"1 bonus action", "components":"VS", "source":"Xanathar's Guide to Everything page 164" }
shatter = { "name":"Shatter", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 275" }
silence = { "name":"Silence", "level":"2nd", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 275" }
skywrite = { "name":"Skywrite", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 22, Xanathar's Guide to Everything page 165" }
snillocssnowballswarm = { "name":"Snilloc's Snowball Swarm", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 22, Xanathar's Guide to Everything page 165" }
spiderclimb = { "name":"Spider Climb", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 277" }
spikegrowth = { "name":"Spike Growth", "level":"2nd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 277" }
spiritualweapon = { "name":"Spiritual Weapon", "level":"2nd", "school":"Evocation", "castingtime":"1 bonus action", "components":"VS", "source":"Player Handbook page 278" }
suggestion = { "name":"Suggestion", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VM", "source":"Player Handbook page 279" }
wardingbond = { "name":"Warding Bond", "level":"2nd", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 287" }
wardingwind = { "name":"Warding Wind", "level":"2nd", "school":"Evocation", "castingtime":"1 action", "components":"V", "source":"EE 23, Xanathar's Guide to Everything page 170" }
web = { "name":"Web", "level":"2nd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 287" }
zoneoftruth = { "name":"Zone of Truth", "level":"2nd", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 289" }
animatedead = { "name":"Animate Dead", "level":"3rd", "school":"Necromancy", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 212" }
auraofvitality = { "name":"Aura of Vitality", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 216" }
beaconofhope = { "name":"Beacon of Hope", "level":"3rd", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 217" }
bestowcurse = { "name":"Bestow Curse", "level":"3rd", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 218" }
blindingsmite = { "name":"Blinding Smite", "level":"3rd", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 219" }
blink = { "name":"Blink", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 219" }
calllightning = { "name":"Call Lightning", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 220" }
catnap = { "name":"Catnap", "level":"3rd", "school":"Enchantment", "castingtime":"1 action", "components":"SM", "source":"Xanathar's Guide to Everything page 151" }
clairvoyance = { "name":"Clairvoyance", "level":"3rd", "school":"Divination", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 222" }
conjureanimals = { "name":"Conjure Animals", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 225" }
conjurebarrage = { "name":"Conjure Barrage", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 225" }
counterspell = { "name":"Counterspell", "level":"3rd", "school":"Abjuration", "castingtime":"1 reaction", "components":"S", "source":"Player Handbook page 228" }
createfoodandwater = { "name":"Create Food and Water", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 229" }
crusadersmantle = { "name":"Crusader's Mantle", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 230" }
daylight = { "name":"Daylight", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 230" }
dispelmagic = { "name":"Dispel Magic", "level":"3rd", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 234" }
elementalweapon = { "name":"Elemental Weapon", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 237" }
enemiesabound = { "name":"Enemies Abound", "level":"3rd", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 155" }
eruptingearth = { "name":"Erupting Earth", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"EE 17, Xanathar's Guide to Everything page 155" }
fear = { "name":"Fear", "level":"3rd", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 239" }
feigndeath = { "name":"Feign Death", "level":"3rd", "school":"Necromancy", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 240" }
fireball = { "name":"Fireball", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 241" }
flamearrows = { "name":"Flame Arrows", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 18, Xanathar's Guide to Everything page 156" }
fly = { "name":"Fly", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 243" }
gaseousform = { "name":"Gaseous Form", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 244" }
glyphofwarding = { "name":"Glyph of Warding", "level":"3rd", "school":"Abjuration", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 245" }
haste = { "name":"Haste", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 250" }
hungerofhadar = { "name":"Hunger of Hadar", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 251" }
hypnoticpattern = { "name":"Hypnotic Pattern", "level":"3rd", "school":"Illusion", "castingtime":"1 action", "components":"SM", "source":"Player Handbook page 252" }
leomundstinyhut = { "name":"Leomund's Tiny Hut", "level":"3rd", "school":"Evocation", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 255" }
lifetransference = { "name":"Life Transference", "level":"3rd", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 160" }
lightningarrow = { "name":"Lightning Arrow", "level":"3rd", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VS", "source":"Player Handbook page 255" }
lightningbolt = { "name":"Lightning Bolt", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 255" }
magiccircle = { "name":"Magic Circle", "level":"3rd", "school":"Abjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 256" }
majorimage = { "name":"Major Image", "level":"3rd", "school":"Illusion", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 258" }
masshealingword = { "name":"Mass Healing Word", "level":"3rd", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 258" }
meldintostone = { "name":"Meld into Stone", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 259" }
melfsminutemeteors = { "name":"Melf's Minute Meteors", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 20, Xanathar's Guide to Everything page 161" }
nondetection = { "name":"Nondetection", "level":"3rd", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 263" }
phantomsteed = { "name":"Phantom Steed", "level":"3rd", "school":"Illusion", "castingtime":"1 minute", "components":"VS", "source":"Player Handbook page 265" }
plantgrowth = { "name":"Plant Growth", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 266" }
protectionfromenergy = { "name":"Protection from Energy", "level":"3rd", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 270" }
removecurse = { "name":"Remove Curse", "level":"3rd", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 271" }
revivify = { "name":"Revivify", "level":"3rd", "school":"Necromancy", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 272" }
sending = { "name":"Sending", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 274" }
sleetstorm = { "name":"Sleet Storm", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 276" }
slow = { "name":"Slow", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 277" }
speakwithdead = { "name":"Speak with Dead", "level":"3rd", "school":"Necromancy", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 277" }
speakwithplants = { "name":"Speak with Plants", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 277" }
spiritguardians = { "name":"Spirit Guardians", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 278" }
stinkingcloud = { "name":"Stinking Cloud", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 278" }
summonlesserdemons = { "name":"Summon Lesser Demons", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Xanathar's Guide to Everything page 167" }
thunderstep = { "name":"Thunder Step", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"V", "source":"Xanathar's Guide to Everything page 168" }
tidalwave = { "name":"Tidal Wave", "level":"3rd", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"EE 22, Xanathar's Guide to Everything page 168" }
tinyservant = { "name":"Tiny Servant", "level":"3rd", "school":"Transmutation", "castingtime":"1 minute", "components":"VS", "source":"Xanathar's Guide to Everything page 168" }
tongues = { "name":"Tongues", "level":"3rd", "school":"Divination", "castingtime":"1 action", "components":"VM", "source":"Player Handbook page 283" }
vampirictouch = { "name":"Vampiric Touch", "level":"3rd", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 285" }
wallofsand = { "name":"Wall of Sand", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 23, Xanathar's Guide to Everything page 170" }
wallofwater = { "name":"Wall of Water", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 23, Xanathar's Guide to Everything page 170" }
waterbreathing = { "name":"Water Breathing", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 287" }
waterwalk = { "name":"Water Walk", "level":"3rd", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 287" }
windwall = { "name":"Wind Wall", "level":"3rd", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 288" }
arcaneeye = { "name":"Arcane Eye", "level":"4th", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 214" }
auraoflife = { "name":"Aura of Life", "level":"4th", "school":"Abjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 216" }
auraofpurity = { "name":"Aura of Purity", "level":"4th", "school":"Abjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 216" }
banishment = { "name":"Banishment", "level":"4th", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 217" }
blight = { "name":"Blight", "level":"4th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 219" }
charmmonster = { "name":"Charm Monster", "level":"4th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 151" }
compulsion = { "name":"Compulsion", "level":"4th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 224" }
confusion = { "name":"Confusion", "level":"4th", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 224" }
conjureminorelementals = { "name":"Conjure Minor Elementals", "level":"4th", "school":"Conjuration", "castingtime":"1 minute", "components":"VS", "source":"Player Handbook page 226" }
conjurewoodlandbeings = { "name":"Conjure Woodland Beings", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 226" }
controlwater = { "name":"Control Water", "level":"4th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 227" }
deathward = { "name":"Death Ward", "level":"4th", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 230" }
dimensiondoor = { "name":"Dimension Door", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 233" }
divination = { "name":"Divination", "level":"4th", "school":"Divination", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 234" }
dominatebeast = { "name":"Dominate Beast", "level":"4th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 234" }
elementalbane = { "name":"Elemental Bane", "level":"4th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 17, Xanathar's Guide to Everything page 155" }
evardsblacktentacles = { "name":"Evard's Black Tentacles", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 238" }
fabricate = { "name":"Fabricate", "level":"4th", "school":"Transmutation", "castingtime":"10 minutes", "components":"VS", "source":"Player Handbook page 239" }
findgreatersteed = { "name":"Find Greater Steed", "level":"4th", "school":"Conjuration", "castingtime":"10 minutes", "components":"VS", "source":"Xanathar's Guide to Everything page 156" }
fireshield = { "name":"Fire Shield", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 242" }
freedomofmovement = { "name":"Freedom of Movement", "level":"4th", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 244" }
giantinsect = { "name":"Giant Insect", "level":"4th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 245" }
graspingvine = { "name":"Grasping Vine", "level":"4th", "school":"Conjuration", "castingtime":"1 bonus action", "components":"VS", "source":"Player Handbook page 246" }
greaterinvisibility = { "name":"Greater Invisibility", "level":"4th", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 246" }
guardianoffaith = { "name":"Guardian of Faith", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 246" }
guardianofnature = { "name":"Guardian of Nature", "level":"4th", "school":"Transmutation", "castingtime":"1 bonus action", "components":"V", "source":"Xanathar's Guide to Everything page 157" }
hallucinatoryterrain = { "name":"Hallucinatory Terrain", "level":"4th", "school":"Illusion", "castingtime":"10 minutes", "components":"VSM", "source":"Player Handbook page 249" }
icestorm = { "name":"Ice Storm", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 252" }
leomundssecretchest = { "name":"Leomund's Secret Chest", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 254" }
locatecreature = { "name":"Locate Creature", "level":"4th", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 256" }
mordenkainensfaithfulhound = { "name":"Mordenkainen's Faithful Hound", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 261" }
mordenkainensprivatesanctum = { "name":"Mordenkainen's Private Sanctum", "level":"4th", "school":"Abjuration", "castingtime":"10 minutes", "components":"VSM", "source":"Player Handbook page 262" }
otilukesresilientsphere = { "name":"Otiluke's Resilient Sphere", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 264" }
phantasmalkiller = { "name":"Phantasmal Killer", "level":"4th", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 265" }
polymorph = { "name":"Polymorph", "level":"4th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 266" }
shadowofmoil = { "name":"Shadow of Moil", "level":"4th", "school":"Necromancy", "castingtime":"1 action", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 164" }
sickeningradiance = { "name":"Sickening Radiance", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 164" }
staggeringsmite = { "name":"Staggering Smite", "level":"4th", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 278" }
stoneshape = { "name":"Stone Shape", "level":"4th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 278" }
stoneskin = { "name":"Stoneskin", "level":"4th", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 278" }
stormsphere = { "name":"Storm Sphere", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"EE 22, Xanathar's Guide to Everything page 166" }
summongreaterdemon = { "name":"Summon Greater Demon", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Xanathar's Guide to Everything page 166" }
vitriolicsphere = { "name":"Vitriolic Sphere", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 23, Xanathar's Guide to Everything page 170" }
walloffire = { "name":"Wall of Fire", "level":"4th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 285" }
waterysphere = { "name":"Watery Sphere", "level":"4th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"EE 23, Xanathar's Guide to Everything page 170" }
animateobjects = { "name":"Animate Objects", "level":"5th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 213" }
antilifeshell = { "name":"Antilife Shell", "level":"5th", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 213" }
awaken = { "name":"Awaken", "level":"5th", "school":"Transmutation", "castingtime":"8 hours", "components":"VSMgp", "source":"Player Handbook page 216" }
banishingsmite = { "name":"Banishing Smite", "level":"5th", "school":"Abjuration", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 216" }
bigbyshand = { "name":"Bigby's Hand", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 218" }
circleofpower = { "name":"Circle of Power", "level":"5th", "school":"Abjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 221" }
cloudkill = { "name":"Cloudkill", "level":"5th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 222" }
commune = { "name":"Commune", "level":"5th", "school":"Divination", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 223" }
communewithnature = { "name":"Commune with Nature", "level":"5th", "school":"Divination", "castingtime":"1 minute", "components":"VS", "source":"Player Handbook page 224" }
coneofcold = { "name":"Cone of Cold", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 224" }
conjureelemental = { "name":"Conjure Elemental", "level":"5th", "school":"Conjuration", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 225" }
conjurevolley = { "name":"Conjure Volley", "level":"5th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 226" }
contactotherplane = { "name":"Contact Other Plane", "level":"5th", "school":"Divination", "castingtime":"1 minute", "components":"V", "source":"Player Handbook page 226" }
contagion = { "name":"Contagion", "level":"5th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 227" }
controlwinds = { "name":"Control Winds", "level":"5th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 16" }
creation = { "name":"Creation", "level":"5th", "school":"Illusion", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 229" }
dansemacabre = { "name":"Danse Macabre", "level":"5th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 153" }
dawn = { "name":"Dawn", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 153" }
destructivewave = { "name":"Destructive Wave", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 231" }
dispelevilandgood = { "name":"Dispel Evil and Good", "level":"5th", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 233" }
dominateperson = { "name":"Dominate Person", "level":"5th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 235" }
dream = { "name":"Dream", "level":"5th", "school":"Illusion", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 236" }
enervation = { "name":"Enervation", "level":"5th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 155" }
farstep = { "name":"Far Step", "level":"5th", "school":"Conjuration", "castingtime":"1 bonus action", "components":"V", "source":"Xanathar's Guide to Everything page 155" }
flamestrike = { "name":"Flame Strike", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 242" }
geas = { "name":"Geas", "level":"5th", "school":"Enchantment", "castingtime":"1 minute", "components":"V", "source":"Player Handbook page 244" }
greaterrestoration = { "name":"Greater Restoration", "level":"5th", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 246" }
hallow = { "name":"Hallow", "level":"5th", "school":"Evocation", "castingtime":"24 hours", "components":"VSMgp", "source":"Player Handbook page 249" }
holdmonster = { "name":"Hold Monster", "level":"5th", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 251" }
holyweapon = { "name":"Holy Weapon", "level":"5th", "school":"Evocation", "castingtime":"1 bonus action", "components":"VS", "source":"Xanathar's Guide to Everything page 157" }
immolation = { "name":"Immolation", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"V", "source":"EE 19, Xanathar's Guide to Everything page 158" }
infernalcalling = { "name":"Infernal Calling", "level":"5th", "school":"Conjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 158" }
insectplague = { "name":"Insect Plague", "level":"5th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 254" }
legendlore = { "name":"Legend Lore", "level":"5th", "school":"Divination", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 254" }
maelstrom = { "name":"Maelstrom", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"EE 20, Xanathar's Guide to Everything page 160" }
masscurewounds = { "name":"Mass Cure Wounds", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 258" }
mislead = { "name":"Mislead", "level":"5th", "school":"Illusion", "castingtime":"1 action", "components":"S", "source":"Player Handbook page 260" }
modifymemory = { "name":"Modify Memory", "level":"5th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 261" }
negativeenergyflood = { "name":"Negative Energy Flood", "level":"5th", "school":"Necromancy", "castingtime":"1 action", "components":"VM", "source":"Xanathar's Guide to Everything page 163" }
passwall = { "name":"Passwall", "level":"5th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 264" }
planarbinding = { "name":"Planar Binding", "level":"5th", "school":"Abjuration", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 265" }
raisedead = { "name":"Raise Dead", "level":"5th", "school":"Necromancy", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 270" }
rarystelepathicbond = { "name":"Rary's Telepathic Bond", "level":"5th", "school":"Divination", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 270" }
reincarnate = { "name":"Reincarnate", "level":"5th", "school":"Transmutation", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 271" }
scrying = { "name":"Scrying", "level":"5th", "school":"Divination", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 273" }
seeming = { "name":"Seeming", "level":"5th", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 274" }
skillempowerment = { "name":"Skill Empowerment", "level":"5th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 165" }
steelwindstrike = { "name":"Steel Wind Strike", "level":"5th", "school":"Conjuration", "castingtime":"1 action", "components":"SMgp", "source":"Xanathar's Guide to Everything page 166" }
swiftquiver = { "name":"Swift Quiver", "level":"5th", "school":"Transmutation", "castingtime":"1 bonus action", "components":"VSM", "source":"Player Handbook page 279" }
synapticstatic = { "name":"Synaptic Static", "level":"5th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 167" }
telekinesis = { "name":"Telekinesis", "level":"5th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 280" }
teleportationcircle = { "name":"Teleportation Circle", "level":"5th", "school":"Conjuration", "castingtime":"1 minute", "components":"VMgp", "source":"Player Handbook page 282" }
transmuterock = { "name":"Transmute Rock", "level":"5th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"EE 22, Xanathar's Guide to Everything page 169" }
treestride = { "name":"TrEE Stride", "level":"5th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 283" }
wallofforce = { "name":"Wall of Force", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 285" }
walloflight = { "name":"Wall of Light", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Xanathar's Guide to Everything page 170" }
wallofstone = { "name":"Wall of Stone", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 287" }
wrathofnature = { "name":"Wrath of Nature", "level":"5th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 171" }
arcanegate = { "name":"Arcane Gate", "level":"6th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 214" }
bladebarrier = { "name":"Blade Barrier", "level":"6th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 218" }
bonesoftheearth = { "name":"Bones of the Earth", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 15, Xanathar's Guide to Everything page 150" }
chainlightning = { "name":"Chain Lightning", "level":"6th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 221" }
circleofdeath = { "name":"Circle of Death", "level":"6th", "school":"Necromancy", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 221" }
conjurefey = { "name":"Conjure Fey", "level":"6th", "school":"Conjuration", "castingtime":"1 minute", "components":"VS", "source":"Player Handbook page 226" }
contingency = { "name":"Contingency", "level":"6th", "school":"Evocation", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 227" }
createhomunculus = { "name":"Create Homunculus", "level":"6th", "school":"Transmutation", "castingtime":"1 hour", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 152" }
createundead = { "name":"Create Undead", "level":"6th", "school":"Necromancy", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 229" }
disintegrate = { "name":"Disintegrate", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 233" }
drawmijsinstantsummons = { "name":"Drawmij's Instant Summons", "level":"6th", "school":"Conjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 235" }
druidgrove = { "name":"Druid Grove", "level":"6th", "school":"Abjuration", "castingtime":"10 minutes", "components":"VSM", "source":"Xanathar's Guide to Everything page 154" }
eyebite = { "name":"Eyebite", "level":"6th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 238" }
findthepath = { "name":"Find the Path", "level":"6th", "school":"Divination", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 240" }
fleshtostone = { "name":"Flesh to Stone", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 243" }
forbiddance = { "name":"Forbiddance", "level":"6th", "school":"Abjuration", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 243" }
globeofinvulnerability = { "name":"Globe of Invulnerability", "level":"6th", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 245" }
guardsandwards = { "name":"Guards and Wards", "level":"6th", "school":"Abjuration", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 248" }
harm = { "name":"Harm", "level":"6th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 249" }
heal = { "name":"Heal", "level":"6th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 250" }
heroesfeast = { "name":"Heroes' Feast", "level":"6th", "school":"Conjuration", "castingtime":"10 minutes", "components":"VSMgp", "source":"Player Handbook page 250" }
investitureofflame = { "name":"Investiture of Flame", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 19, Xanathar's Guide to Everything page 159" }
investitureofice = { "name":"Investiture of Ice", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 19, Xanathar's Guide to Everything page 159" }
investitureofstone = { "name":"Investiture of Stone", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 19, Xanathar's Guide to Everything page 159" }
investitureofwind = { "name":"Investiture of Wind", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"EE 20, Xanathar's Guide to Everything page 160" }
magicjar = { "name":"Magic Jar", "level":"6th", "school":"Necromancy", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 257" }
masssuggestion = { "name":"Mass Suggestion", "level":"6th", "school":"Enchantment", "castingtime":"1 action", "components":"VM", "source":"Player Handbook page 258" }
mentalprison = { "name":"Mental Prison", "level":"6th", "school":"Illusion", "castingtime":"1 action", "components":"S", "source":"Xanathar's Guide to Everything page 161" }
moveearth = { "name":"Move Earth", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 263" }
otilukesfreezingsphere = { "name":"Otiluke's Freezing Sphere", "level":"6th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 263" }
ottosirresistibledance = { "name":"Otto's Irresistible Dance", "level":"6th", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 264" }
planarally = { "name":"Planar Ally", "level":"6th", "school":"Conjuration", "castingtime":"10 minutes", "components":"VS", "source":"Player Handbook page 265" }
primordialward = { "name":"Primordial Ward", "level":"6th", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"EE 21, Xanathar's Guide to Everything page 163" }
programmedillusion = { "name":"Programmed Illusion", "level":"6th", "school":"Illusion", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 269" }
scatter = { "name":"Scatter", "level":"6th", "school":"Abjuration", "castingtime":"1 action", "components":"V", "source":"Xanathar's Guide to Everything page 164" }
soulcage = { "name":"Soul Cage", "level":"6th", "school":"Necromancy", "castingtime":"1 reaction", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 165" }
sunbeam = { "name":"Sunbeam", "level":"6th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 279" }
tenserstransformation = { "name":"Tenser's Transformation", "level":"6th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Xanathar's Guide to Everything page 168" }
transportviaplants = { "name":"Transport via Plants", "level":"6th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 283" }
trueseeing = { "name":"True Seeing", "level":"6th", "school":"Divination", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 284" }
wallofice = { "name":"Wall of Ice", "level":"6th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 285" }
wallofthorns = { "name":"Wall of Thorns", "level":"6th", "school":"Conjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 287" }
windwalk = { "name":"Wind Walk", "level":"6th", "school":"Transmutation", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 288" }
wordofrecall = { "name":"Word of Recall", "level":"6th", "school":"Conjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 289" }
conjurecelestial = { "name":"Conjure Celestial", "level":"7th", "school":"Conjuration", "castingtime":"1 minute", "components":"VS", "source":"Player Handbook page 225" }
crownofstars = { "name":"Crown of Stars", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Xanathar's Guide to Everything page 152" }
delayedblastfireball = { "name":"Delayed Blast Fireball", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 230" }
divineword = { "name":"Divine Word", "level":"7th", "school":"Evocation", "castingtime":"1 bonus action", "components":"V", "source":"Player Handbook page 234" }
etherealness = { "name":"Etherealness", "level":"7th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 238" }
fingerofdeath = { "name":"Finger of Death", "level":"7th", "school":"Necromancy", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 241" }
firestorm = { "name":"Fire Storm", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 242" }
forcecage = { "name":"Forcecage", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 243" }
miragearcane = { "name":"Mirage Arcane", "level":"7th", "school":"Illusion", "castingtime":"10 minutes", "components":"VS", "source":"Player Handbook page 260" }
mordenkainensmagnificentmansion = { "name":"Mordenkainen's Magnificent Mansion", "level":"7th", "school":"Conjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 261" }
mordenkainenssword = { "name":"Mordenkainen's Sword", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 262" }
planeshift = { "name":"Plane Shift", "level":"7th", "school":"Conjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 266" }
powerwordpain = { "name":"Power Word Pain", "level":"7th", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Xanathar's Guide to Everything page 163" }
prismaticspray = { "name":"Prismatic Spray", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 267" }
projectimage = { "name":"Project Image", "level":"7th", "school":"Illusion", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 270" }
regenerate = { "name":"Regenerate", "level":"7th", "school":"Transmutation", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 271" }
resurrection = { "name":"Resurrection", "level":"7th", "school":"Necromancy", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 272" }
reversegravity = { "name":"Reverse Gravity", "level":"7th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 272" }
sequester = { "name":"Sequester", "level":"7th", "school":"Transmutation", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 274" }
simulacrum = { "name":"Simulacrum", "level":"7th", "school":"Illusion", "castingtime":"12 hours", "components":"VSMgp", "source":"Player Handbook page 276" }
symbol = { "name":"Symbol", "level":"7th", "school":"Abjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 280" }
teleport = { "name":"Teleport", "level":"7th", "school":"Conjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 281" }
templeofthegods = { "name":"Temple of the Gods", "level":"7th", "school":"Conjuration", "castingtime":"1 hour", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 167" }
whirlwind = { "name":"Whirlwind", "level":"7th", "school":"Evocation", "castingtime":"1 action", "components":"VM", "source":"EE 24, Xanathar's Guide to Everything page 171" }
abidalzimshorridwilting = { "name":"Abi-Dalzim's Horrid Wilting", "level":"8th", "school":"Necromancy", "castingtime":"1 action", "components":"VSM", "source":"EE 15, Xanathar's Guide to Everything page 150" }
animalshapes = { "name":"Animal Shapes", "level":"8th", "school":"Transmutation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 212" }
antimagicfield = { "name":"Antimagic Field", "level":"8th", "school":"Abjuration", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 213" }
antipathysympathy = { "name":"Antipathy/Sympathy", "level":"8th", "school":"Enchantment", "castingtime":"1 hour", "components":"VSM", "source":"Player Handbook page 214" }
clone = { "name":"Clone", "level":"8th", "school":"Necromancy", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 222" }
controlweather = { "name":"Control Weather", "level":"8th", "school":"Transmutation", "castingtime":"10 minutes", "components":"VSM", "source":"Player Handbook page 228" }
demiplane = { "name":"Demiplane", "level":"8th", "school":"Conjuration", "castingtime":"1 action", "components":"S", "source":"Player Handbook page 231" }
dominatemonster = { "name":"Dominate Monster", "level":"8th", "school":"Enchantment", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 235" }
earthquake = { "name":"Earthquake", "level":"8th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 236" }
feeblemind = { "name":"Feeblemind", "level":"8th", "school":"Enchantment", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 239" }
glibness = { "name":"Glibness", "level":"8th", "school":"Transmutation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 245" }
holyaura = { "name":"Holy Aura", "level":"8th", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 251" }
illusorydragon = { "name":"Illusory Dragon", "level":"8th", "school":"Illusion", "castingtime":"1 action", "components":"S", "source":"Xanathar's Guide to Everything page 157" }
incendiarycloud = { "name":"Incendiary Cloud", "level":"8th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 253" }
maddeningdarkness = { "name":"Maddening Darkness", "level":"8th", "school":"Evocation", "castingtime":"1 action", "components":"VM", "source":"Xanathar's Guide to Everything page 160" }
maze = { "name":"Maze", "level":"8th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 258" }
mightyfortress = { "name":"Mighty Fortress", "level":"8th", "school":"Conjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 161" }
mindblank = { "name":"Mind Blank", "level":"8th", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 259" }
powerwordstun = { "name":"Power Word Stun", "level":"8th", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 267" }
sunburst = { "name":"Sunburst", "level":"8th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 279" }
telepathy = { "name":"Telepathy", "level":"8th", "school":"Evocation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 281" }
tsunami = { "name":"Tsunami", "level":"8th", "school":"Conjuration", "castingtime":"1 minute", "components":"VS", "source":"Player Handbook page 284" }
astralprojection = { "name":"Astral Projection", "level":"9th", "school":"Necromancy", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 215" }
foresight = { "name":"Foresight", "level":"9th", "school":"Divination", "castingtime":"1 minute", "components":"VSM", "source":"Player Handbook page 244" }
gate = { "name":"Gate", "level":"9th", "school":"Conjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 244" }
imprisonment = { "name":"Imprisonment", "level":"9th", "school":"Abjuration", "castingtime":"1 minute", "components":"VSMgp", "source":"Player Handbook page 252" }
invulnerability = { "name":"Invulnerability", "level":"9th", "school":"Abjuration", "castingtime":"1 action", "components":"VSMgp", "source":"Xanathar's Guide to Everything page 160" }
massheal = { "name":"Mass Heal", "level":"9th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 258" }
masspolymorph = { "name":"Mass Polymorph", "level":"9th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Xanathar's Guide to Everything page 160" }
meteorswarm = { "name":"Meteor Swarm", "level":"9th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 259" }
powerwordheal = { "name":"Power Word Heal", "level":"9th", "school":"Evocation", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 266" }
powerwordkill = { "name":"Power Word Kill", "level":"9th", "school":"Enchantment", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 266" }
prismaticwall = { "name":"Prismatic Wall", "level":"9th", "school":"Abjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 267" }
psychicscream = { "name":"Psychic Scream", "level":"9th", "school":"Enchantment", "castingtime":"1 action", "components":"S", "source":"Xanathar's Guide to Everything page 163" }
shapechange = { "name":"Shapechange", "level":"9th", "school":"Transmutation", "castingtime":"1 action", "components":"VSMgp", "source":"Player Handbook page 274" }
stormofvengeance = { "name":"Storm of Vengeance", "level":"9th", "school":"Conjuration", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 279" }
timestop = { "name":"Time Stop", "level":"9th", "school":"Transmutation", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 283" }
truepolymorph = { "name":"True Polymorph", "level":"9th", "school":"Transmutation", "castingtime":"1 action", "components":"VSM", "source":"Player Handbook page 283" }
trueresurrection = { "name":"True Resurrection", "level":"9th", "school":"Necromancy", "castingtime":"1 hour", "components":"VSMgp", "source":"Player Handbook page 284" }
weird = { "name":"Weird", "level":"9th", "school":"Illusion", "castingtime":"1 action", "components":"VS", "source":"Player Handbook page 288" }
wish = { "name":"Wish", "level":"9th", "school":"Conjuration", "castingtime":"1 action", "components":"V", "source":"Player Handbook page 288" }

oneDictToRuleThemAll = {"acidsplash":acidsplash, "bladeward":bladeward, "chilltouch":chilltouch, "controlflames":controlflames, "createbonfire":createbonfire, "dancinglights":dancinglights, "druidcraft":druidcraft, "eldritchblast":eldritchblast, "firebolt":firebolt, "friends":friends, "frostbite":frostbite, "guidance":guidance, "gust":gust, "infestation":infestation, "light":light, "magehand":magehand, "magicstone":magicstone, "mending":mending, "message":message, "minorillusion":minorillusion, "moldearth":moldearth, "poisonspray":poisonspray, "prestidigitation":prestidigitation, "primalsavagery":primalsavagery, "produceflame":produceflame, "rayoffrost":rayoffrost, "resistance":resistance, "sacredflame":sacredflame, "shapewater":shapewater, "shillelagh":shillelagh, "shockinggrasp":shockinggrasp, "sparethedying":sparethedying, "thaumaturgy":thaumaturgy, "thornwhip":thornwhip, "thunderclap":thunderclap, "tollthedead":tollthedead, "truestrike":truestrike, "viciousmockery":viciousmockery, "wordofradiance":wordofradiance, "absorbelements":absorbelements, "alarm":alarm, "animalfriendship":animalfriendship, "arcaneweapon":arcaneweapon, "armorofagathys":armorofagathys, "armsofhadar":armsofhadar, "bane":bane, "beastbond":beastbond, "bless":bless, "burninghands":burninghands, "catapult":catapult, "causefear":causefear, "ceremony":ceremony, "chaosbolt":chaosbolt, "charmperson":charmperson, "chromaticorb":chromaticorb, "colorspray":colorspray, "command":command, "compelledduel":compelledduel, "comprehendlanguages":comprehendlanguages, "createordestroywater":createordestroywater, "curewounds":curewounds, "detectevilandgood":detectevilandgood, "detectmagic":detectmagic, "detectpoisonanddisease":detectpoisonanddisease, "disguiseself":disguiseself, "dissonantwhispers":dissonantwhispers, "divinefavor":divinefavor, "earthtremor":earthtremor, "ensnaringstrike":ensnaringstrike, "entangle":entangle, "expeditiousretreat":expeditiousretreat, "faeriefire":faeriefire, "falselife":falselife, "featherfall":featherfall, "findfamiliar":findfamiliar, "fogcloud":fogcloud, "goodberry":goodberry, "grease":grease, "guidingbolt":guidingbolt, "hailofthorns":hailofthorns, "healingword":healingword, "hellishrebuke":hellishrebuke, "heroism":heroism, "hex":hex, "huntersmark":huntersmark, "iceknife":iceknife, "identify":identify, "illusoryscript":illusoryscript, "inflictwounds":inflictwounds, "jump":jump, "longstrider":longstrider, "magearmor":magearmor, "magicmissile":magicmissile, "protectionfromevilandgood":protectionfromevilandgood, "purifyfoodanddrink":purifyfoodanddrink, "rayofsickness":rayofsickness, "sanctuary":sanctuary, "searingsmite":searingsmite, "shield":shield, "shieldoffaith":shieldoffaith, "silentimage":silentimage, "sleep":sleep, "snare":snare, "speakwithanimals":speakwithanimals, "tashashideouslaughter":tashashideouslaughter, "tensersfloatingdisk":tensersfloatingdisk, "thunderoussmite":thunderoussmite, "thunderwave":thunderwave, "unseenservant":unseenservant, "witchbolt":witchbolt, "wrathfulsmite":wrathfulsmite, "zephyrstrike":zephyrstrike, "aganazzarsscorcher":aganazzarsscorcher, "aid":aid, "alterself":alterself, "animalmessenger":animalmessenger, "arcanelock":arcanelock, "augury":augury, "barkskin":barkskin, "beastsense":beastsense, "blindnessdeafness":blindnessdeafness, "blur":blur, "brandingsmite":brandingsmite, "calmemotions":calmemotions, "cloudofdaggers":cloudofdaggers, "continualflame":continualflame, "cordonofarrows":cordonofarrows, "crownofmadness":crownofmadness, "darkness":darkness, "darkvision":darkvision, "detectthoughts":detectthoughts, "dragonsbreath":dragonsbreath, "dustdevil":dustdevil, "earthbind":earthbind, "enhanceability":enhanceability, "enlargereduce":enlargereduce, "enthrall":enthrall, "findsteed":findsteed, "findtraps":findtraps, "flameblade":flameblade, "flamingsphere":flamingsphere, "gentlerepose":gentlerepose, "gustofwind":gustofwind, "healingspirit":healingspirit, "heatmetal":heatmetal, "holdperson":holdperson, "invisibility":invisibility, "knock":knock, "lesserrestoration":lesserrestoration, "levitate":levitate, "locateanimalsorplants":locateanimalsorplants, "locateobject":locateobject, "magicmouth":magicmouth, "magicweapon":magicweapon, "maximiliansearthengrasp":maximiliansearthengrasp, "melfsacidarrow":melfsacidarrow, "mindspike":mindspike, "mirrorimage":mirrorimage, "mistystep":mistystep, "moonbeam":moonbeam, "nystulsmagicaura":nystulsmagicaura, "passwithouttrace":passwithouttrace, "phantasmalforce":phantasmalforce, "prayerofhealing":prayerofhealing, "protectionfrompoison":protectionfrompoison, "pyrotechnics":pyrotechnics, "rayofenfeeblement":rayofenfeeblement, "ropetrick":ropetrick, "scorchingray":scorchingray, "seeinvisibility":seeinvisibility, "shadowblade":shadowblade, "shatter":shatter, "silence":silence, "skywrite":skywrite, "snillocssnowballswarm":snillocssnowballswarm, "spiderclimb":spiderclimb, "spikegrowth":spikegrowth, "spiritualweapon":spiritualweapon, "suggestion":suggestion, "wardingbond":wardingbond, "wardingwind":wardingwind, "web":web, "zoneoftruth":zoneoftruth, "animatedead":animatedead, "auraofvitality":auraofvitality, "beaconofhope":beaconofhope, "bestowcurse":bestowcurse, "blindingsmite":blindingsmite, "blink":blink, "calllightning":calllightning, "catnap":catnap, "clairvoyance":clairvoyance, "conjureanimals":conjureanimals, "conjurebarrage":conjurebarrage, "counterspell":counterspell, "createfoodandwater":createfoodandwater, "crusadersmantle":crusadersmantle, "daylight":daylight, "dispelmagic":dispelmagic, "elementalweapon":elementalweapon, "enemiesabound":enemiesabound, "eruptingearth":eruptingearth, "fear":fear, "feigndeath":feigndeath, "fireball":fireball, "flamearrows":flamearrows, "fly":fly, "gaseousform":gaseousform, "glyphofwarding":glyphofwarding, "haste":haste, "hungerofhadar":hungerofhadar, "hypnoticpattern":hypnoticpattern, "leomundstinyhut":leomundstinyhut, "lifetransference":lifetransference, "lightningarrow":lightningarrow, "lightningbolt":lightningbolt, "magiccircle":magiccircle, "majorimage":majorimage, "masshealingword":masshealingword, "meldintostone":meldintostone, "melfsminutemeteors":melfsminutemeteors, "nondetection":nondetection, "phantomsteed":phantomsteed, "plantgrowth":plantgrowth, "protectionfromenergy":protectionfromenergy, "removecurse":removecurse, "revivify":revivify, "sending":sending, "sleetstorm":sleetstorm, "slow":slow, "speakwithdead":speakwithdead, "speakwithplants":speakwithplants, "spiritguardians":spiritguardians, "stinkingcloud":stinkingcloud, "summonlesserdemons":summonlesserdemons, "thunderstep":thunderstep, "tidalwave":tidalwave, "tinyservant":tinyservant, "tongues":tongues, "vampirictouch":vampirictouch, "wallofsand":wallofsand, "wallofwater":wallofwater, "waterbreathing":waterbreathing, "waterwalk":waterwalk, "windwall":windwall, "arcaneeye":arcaneeye, "auraoflife":auraoflife, "auraofpurity":auraofpurity, "banishment":banishment, "blight":blight, "charmmonster":charmmonster, "compulsion":compulsion, "confusion":confusion, "conjureminorelementals":conjureminorelementals, "conjurewoodlandbeings":conjurewoodlandbeings, "controlwater":controlwater, "deathward":deathward, "dimensiondoor":dimensiondoor, "divination":divination, "dominatebeast":dominatebeast, "elementalbane":elementalbane, "evardsblacktentacles":evardsblacktentacles, "fabricate":fabricate, "findgreatersteed":findgreatersteed, "fireshield":fireshield, "freedomofmovement":freedomofmovement, "giantinsect":giantinsect, "graspingvine":graspingvine, "greaterinvisibility":greaterinvisibility, "guardianoffaith":guardianoffaith, "guardianofnature":guardianofnature, "hallucinatoryterrain":hallucinatoryterrain, "icestorm":icestorm, "leomundssecretchest":leomundssecretchest, "locatecreature":locatecreature, "mordenkainensfaithfulhound":mordenkainensfaithfulhound, "mordenkainensprivatesanctum":mordenkainensprivatesanctum, "otilukesresilientsphere":otilukesresilientsphere, "phantasmalkiller":phantasmalkiller, "polymorph":polymorph, "shadowofmoil":shadowofmoil, "sickeningradiance":sickeningradiance, "staggeringsmite":staggeringsmite, "stoneshape":stoneshape, "stoneskin":stoneskin, "stormsphere":stormsphere, "summongreaterdemon":summongreaterdemon, "vitriolicsphere":vitriolicsphere, "walloffire":walloffire, "waterysphere":waterysphere, "animateobjects":animateobjects, "antilifeshell":antilifeshell, "awaken":awaken, "banishingsmite":banishingsmite, "bigbyshand":bigbyshand, "circleofpower":circleofpower, "cloudkill":cloudkill, "commune":commune, "communewithnature":communewithnature, "coneofcold":coneofcold, "conjureelemental":conjureelemental, "conjurevolley":conjurevolley, "contactotherplane":contactotherplane, "contagion":contagion, "controlwinds":controlwinds, "creation":creation, "dansemacabre":dansemacabre, "dawn":dawn, "destructivewave":destructivewave, "dispelevilandgood":dispelevilandgood, "dominateperson":dominateperson, "dream":dream, "enervation":enervation, "farstep":farstep, "flamestrike":flamestrike, "geas":geas, "greaterrestoration":greaterrestoration, "hallow":hallow, "holdmonster":holdmonster, "holyweapon":holyweapon, "immolation":immolation, "infernalcalling":infernalcalling, "insectplague":insectplague, "legendlore":legendlore, "maelstrom":maelstrom, "masscurewounds":masscurewounds, "mislead":mislead, "modifymemory":modifymemory, "negativeenergyflood":negativeenergyflood, "passwall":passwall, "planarbinding":planarbinding, "raisedead":raisedead, "rarystelepathicbond":rarystelepathicbond, "reincarnate":reincarnate, "scrying":scrying, "seeming":seeming, "skillempowerment":skillempowerment, "steelwindstrike":steelwindstrike, "swiftquiver":swiftquiver, "synapticstatic":synapticstatic, "telekinesis":telekinesis, "teleportationcircle":teleportationcircle, "transmuterock":transmuterock, "treestride":treestride, "wallofforce":wallofforce, "walloflight":walloflight, "wallofstone":wallofstone, "wrathofnature":wrathofnature, "arcanegate":arcanegate, "bladebarrier":bladebarrier, "bonesoftheearth":bonesoftheearth, "chainlightning":chainlightning, "circleofdeath":circleofdeath, "conjurefey":conjurefey, "contingency":contingency, "createhomunculus":createhomunculus, "createundead":createundead, "disintegrate":disintegrate, "drawmijsinstantsummons":drawmijsinstantsummons, "druidgrove":druidgrove, "eyebite":eyebite, "findthepath":findthepath, "fleshtostone":fleshtostone, "forbiddance":forbiddance, "globeofinvulnerability":globeofinvulnerability, "guardsandwards":guardsandwards, "harm":harm, "heal":heal, "heroesfeast":heroesfeast, "investitureofflame":investitureofflame, "investitureofice":investitureofice, "investitureofstone":investitureofstone, "investitureofwind":investitureofwind, "magicjar":magicjar, "masssuggestion":masssuggestion, "mentalprison":mentalprison, "moveearth":moveearth, "otilukesfreezingsphere":otilukesfreezingsphere, "ottosirresistibledance":ottosirresistibledance, "planarally":planarally, "primordialward":primordialward, "programmedillusion":programmedillusion, "scatter":scatter, "soulcage":soulcage, "sunbeam":sunbeam, "tenserstransformation":tenserstransformation, "transportviaplants":transportviaplants, "trueseeing":trueseeing, "wallofice":wallofice, "wallofthorns":wallofthorns, "windwalk":windwalk, "wordofrecall":wordofrecall, "conjurecelestial":conjurecelestial, "crownofstars":crownofstars, "delayedblastfireball":delayedblastfireball, "divineword":divineword, "etherealness":etherealness, "fingerofdeath":fingerofdeath, "firestorm":firestorm, "forcecage":forcecage, "miragearcane":miragearcane, "mordenkainensmagnificentmansion":mordenkainensmagnificentmansion, "mordenkainenssword":mordenkainenssword, "planeshift":planeshift, "powerwordpain":powerwordpain, "prismaticspray":prismaticspray, "projectimage":projectimage, "regenerate":regenerate, "resurrection":resurrection, "reversegravity":reversegravity, "sequester":sequester, "simulacrum":simulacrum, "symbol":symbol, "teleport":teleport, "templeofthegods":templeofthegods, "whirlwind":whirlwind, "abidalzimshorridwilting":abidalzimshorridwilting, "animalshapes":animalshapes, "antimagicfield":antimagicfield, "antipathysympathy":antipathysympathy, "clone":clone, "controlweather":controlweather, "demiplane":demiplane, "dominatemonster":dominatemonster, "earthquake":earthquake, "feeblemind":feeblemind, "glibness":glibness, "holyaura":holyaura, "illusorydragon":illusorydragon, "incendiarycloud":incendiarycloud, "maddeningdarkness":maddeningdarkness, "maze":maze, "mightyfortress":mightyfortress, "mindblank":mindblank, "powerwordstun":powerwordstun, "sunburst":sunburst, "telepathy":telepathy, "tsunami":tsunami, "astralprojection":astralprojection, "foresight":foresight, "gate":gate, "imprisonment":imprisonment, "invulnerability":invulnerability, "massheal":massheal, "masspolymorph":masspolymorph, "meteorswarm":meteorswarm, "powerwordheal":powerwordheal, "powerwordkill":powerwordkill, "prismaticwall":prismaticwall, "psychicscream":psychicscream, "shapechange":shapechange, "stormofvengeance":stormofvengeance, "timestop":timestop, "truepolymorph":truepolymorph, "trueresurrection":trueresurrection, "weird":weird, "wish":wish}