club = { "name":"Club", "price":"1 sp", "damagetype":"1d4 bludgeoning", "weight":"2 lb."}
dagger = { "name":"Dagger", "price":"2 gp", "damagetype":"1d4 piercing", "weight":"1 lb."}
greatclub = { "name":"Greatclub", "price":"2 sp", "damagetype":"1d8 bludgeoning", "weight":"10 lb."}
handaxe = { "name":"Handaxe", "price":"5 gp", "damagetype":"1d6 slashing", "weight":"2 lb."}
javelin = { "name":"Javelin", "price":"5 sp", "damagetype":"1d6 piercing", "weight":"2 lb."}
lighthammer = { "name":"Light hammer", "price":"2 gp", "damagetype":"1d4 bludgeoning", "weight":"2 lb."}
mace = { "name":"Mace", "price":"5 gp", "damagetype":"1d6 bludgeoning", "weight":"4 lb."}
quarterstaff = { "name":"Quarterstaff", "price":"2 sp", "damagetype":"1d6 bludgeoning", "weight":"4 lb."}
crossbowlight = { "name":"Crossbow, light", "price":"25 gp", "damagetype":"1d8 piercing", "weight":"5 lb."}
dart = { "name":"Dart", "price":"5 cp", "damagetype":"1d4 piercing", "weight":"1/4 lb."}
shortbow = { "name":"Shortbow", "price":"25 gp", "damagetype":"1d6 piercing", "weight":"2 lb."}
sling = { "name":"Sling", "price":"1 sp", "damagetype":"1d4 bludgeoning", "weight":"-"}
battleaxe = { "name":"Battleaxe", "price":"10 gp", "damagetype":"1d8 slashing", "weight":"4 lb."}
flail = { "name":"Flail", "price":"10 gp", "damagetype":"1d8 bludgeoning", "weight":"2 lb."}
glaive = { "name":"Glaive", "price":"20 gp", "damagetype":"1d10 slashing", "weight":"6 lb."}
greataxe = { "name":"Greataxe", "price":"30 gp", "damagetype":"1d12 slashing", "weight":"7 lb."}
greatsword = { "name":"Greatsword", "price":"50 gp", "damagetype":"2d6 slashing", "weight":"6 lb."}
halberd = { "name":"Halberd", "price":"20 gp", "damagetype":"1d10 slashing", "weight":"6 lb."}
lance = { "name":"Lance", "price":"10 gp", "damagetype":"1d12 piercing", "weight":"6 lb."}
longsword = { "name":"Longsword", "price":"15 gp", "damagetype":"1d8 slashing", "weight":"3 lb."}
maul = { "name":"Maul", "price":"10 gp", "damagetype":"2d6 bludgeoning", "weight":"10 lb."}
morningstar = { "name":"Morningstar", "price":"15 gp", "damagetype":"1d8 piercing", "weight":"4 lb."}
pike = { "name":"Pike", "price":"5 gp", "damagetype":"1d10 piercing", "weight":"18 lb."}
rapier = { "name":"Rapier", "price":"25 gp", "damagetype":"1d8 piercing", "weight":"2 lb."}
scimitar = { "name":"Scimitar", "price":"25 gp", "damagetype":"1d6 slashing", "weight":"3 lb."}
shortsword = { "name":"Shortsword", "price":"10 gp", "damagetype":"1d6 piercing", "weight":"2 lb."}
trident = { "name":"Trident", "price":"5 gp", "damagetype":"1d6 piercing", "weight":"4 lb."}
warpick = { "name":"War pick", "price":"5 gp", "damagetype":"1d8 piercing", "weight":"2 lb."}
warhammer = { "name":"Warhammer", "price":"15 gp", "damagetype":"1d8 bludgeoning", "weight":"2 lb."}
whip = { "name":"Whip", "price":"2 gp", "damagetype":"1d4 slashing", "weight":"3 lb."}
blowgun = { "name":"Blowgun", "price":"10 gp", "damagetype":"1 piercing", "weight":"1 lb."}
crossbowhand = { "name":"Crossbow, hand", "price":"75 gp", "damagetype":"1d6 piercing", "weight":"3 lb."}
crossbowheavy = { "name":"Crossbow, heavy", "price":"50 gp", "damagetype":"1d10 piercing", "weight":"18 lb."}
longbow = { "name":"Longbow", "price":"50 gp", "damagetype":"1d8 piercing", "weight":"2 lb."}
net = { "name":"Net", "price":"1 gp", "damagetype":"-", "weight":"3 lb."}

oneDictToRuleThemAll = {"club":club, "dagger":dagger, "greatclub":greatclub, "handaxe":handaxe, "javelin":javelin, "lighthammer":lighthammer, "mace":mace, "quarterstaff":quarterstaff, "crossbowlight":crossbowlight, "dart":dart, "shortbow":shortbow, "sling":sling, "battleaxe":battleaxe, "flail":flail, "glaive":glaive, "greataxe":greataxe, "greatsword":greatsword, "halberd":halberd, "lance":lance, "longsword":longsword, "maul":maul, "morningstar":morningstar, "pike":pike, "rapier":rapier, "scimitar":scimitar, "shortsword":shortsword, "trident":trident, "warpick":warpick, "warhammer":warhammer, "whip":whip, "blowgun":blowgun, "crossbowhand":crossbowhand, "crossbowheavy":crossbowheavy, "longbow":longbow, "net":net}